spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
