spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: file:///Users/vishanchathuranga/Documents/TaskFlow-System/config-repo/gcp-credentials.json
        project-id: taskflow-project-id
        
gcp:
  bucket:
    name: taskflow-bucket

jwt:
  secret: 496a84eb827a44f4ac1c3c3a9d701ed6496a84eb827a44f4ac1c3c3a9d701ed6
